on: [ push, pull_request ]
name: Build
jobs:
  build:
    strategy:
      matrix:
        go-version: [ 1.21.x ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - uses: knicknic/os-specific-run@v1
        with:
          linux:
            export CGO_ENABLED=1
            export GOOS=linux
            GOARCH=amd64 go build -o dist/libktanemod-remote-math-interface.so -buildmode=c-shared .
            GOARCH=386 go build -o dist/libktanemod-remote-math-interface.so -buildmode=c-shared .
            GOARCH=arm64 go build -o dist/libktanemod-remote-math-interface.so -buildmode=c-shared .
            GOARCH=amd go build -o dist/libktanemod-remote-math-interface.so -buildmode=c-shared .
          windows: |
            set CGO_ENABLED=1
            set GOOS=windows
            set GOARCH=amd64
            go build -o dist/ktanemod-remote-math-interface-x64.dll -buildmode=c-shared .
            set GOARCH=386
            go build -o dist/ktanemod-remote-math-interface-x86.dll -buildmode=c-shared .
            set GOARCH=arm64
            go build -o dist/ktanemod-remote-math-interface-x86.dll -buildmode=c-shared .
            set GOARCH=arm
            go build -o dist/ktanemod-remote-math-interface-x86.dll -buildmode=c-shared .
          macos: |
            export CGO_ENABLED=1
            export GOOS=darwin
            export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
            GOARCH=amd64 go build -o dist/ktanemod-remote-math-interface-amd64.dylib -buildmode=c-shared .
            GOARCH=arm64 go build -o dist/ktanemod-remote-math-interface-arm64.dylib -buildmode=c-shared .
      - uses: actions/upload-artifact@v2.2.1
        with:
          name: dist
          path: dist

  release:
    name: Release binaries
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Create Release and Attach Binaries
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -x
          assets=()
          for asset in ./dist/*; do
            assets+=("$asset")
          done
          githubref=${{ github.ref }}
          version="${githubref##*/}"
          gh release create "${version}" -t "${version}"
          gh release upload "${version}" "${assets[@]}"
